---
# Global variables for the Mesos cluster

# the port at which the clients will connect
zookeeper_client_port:      2181

# needed by the mesos roles
only_master:        "no"
only_slave:         "no"

# needed by the zooker role
only_server:        "no"
only_client:        "no"

# Mesos slave parameters -------------------------------------

mesos_containerizers:
  - docker
  - mesos

mesos_resources:
  cpus:     3
  memory:   1024
  disk:     10140
  ports:    "30000-40000"

# TBC --------------------------------------------------------

mesos_dir:              /mesos

mesos_version:          0.20.0
mesos_git_tag:          0.17.0-rc2
protobuf_version:       2.5.0

mesos_deps:             [ "git", "zip", "python-pip" ]
mesos_pip_deps:         []

mesos_artifacts_dir:    /opt/mesos/artifacts.dir
mesos_build_links:      /tmp

mesos_cluster: {

    zookeeper:    'zk://zk1:2181,zk2:2181,zk3:2181/mesos',
    logs:         /mesos/log,
    runs:         /mesos/run,
    disk_space:   16384
}
