---
# Install and configure Zookeper 

# ---------------------------------------------------------------------

- include_vars: "{{ item }}"
  with_first_found:
   - "zookeeper-{{ ansible_distribution }}.yml"
   - "zookeeper-{{ ansible_os_family }}.yml"

# ---------------------------------------------------------------------

- include: server.yml
  tags:: server

- include: client.yml
  tags:: client
