---
# Install and configure Zookeper 

# ---------------------------------------------------------------------

- include_vars: "{{ item }}"
  with_first_found:
   - "zookeeper-{{ ansible_distribution }}.yml"
   - "zookeeper-{{ ansible_os_family }}.yml"

# ---------------------------------------------------------------------

- include: server.yml
  when: only_server == "yes"

- include: client.yml
  when: only_client == "yes"
