---
# Install and configure Zookeper 

- name: Install Zookeeper package
  yum: state=present name={{ item }}
  with_items:
  - zookeeper
  - zookeeper-server

- name: Create configuration files
  template: src={{ item }} dest=/etc/zookeeper/{{ item | replace(".j2", "") }}
  			backup=yes
  with_items:
  - zoo.cfg.j2
  - log4j.properties.j2
