---
# Build Mesos cluster and frameworks

- hosts: mesos-cluster

  pre_tasks:

    - include_vars: "{{ item }}"
      with_first_found:
       - "group_vars/all-{{ ansible_distribution }}.yml"
       - "group_vars/all-{{ ansible_os_family }}.yml"

  tasks:

    - name: Install nice-to-have packages
      sudo: yes
      yum: state=present name={{ item }}
      when: ansible_pkg_mgr == "yum"
      with_items: desired_packages_to_install

# ---------------------------------------------------------------------
#  Zookeeper cluster
# ---------------------------------------------------------------------

- hosts: zookeepers
  roles:

    - { role: zookeeper, tags: server, sudo: yes }

- hosts: mesos-masters
  roles:

    - { role: zookeeper, tags: client, sudo: yes }
    - { role: mesos,     tags: master, sudo: yes }

- hosts: mesos-slaves
  roles:

    - { role: zookeeper, tags: client, sudo: yes }
    - { role: mesos,     tags: slave,  sudo: yes }

# TBC ------------------------------------------------------

# - hosts: build
#   vars_files:
#     - "group_vars/mesos_packages.yml"

#   roles:
#     - { role: mesos_build_source, tags: mesos_build_src }

# - hosts: mesos
#   vars_files:
#     - "group_vars/mesos_packages.yml"

#   pre_tasks:
#   - include: tasks/prerequisites.yml

#   roles:
#     - { role: zookeeper, sudo: yes }
#     - { role: mesos_from_source,   when: ansible_distribution not in os_mesos_ready_packages }

#   post_tasks:
#     - include: tasks/package.yml
