---
# Create directories, install required software packages, etc.

- name: Create build directory
  file: state=directory path={{ mesos_dir }}

- name: Install pre-requisite software packages
  sudo: yes
  apt: name={{ item }} state=present
  with_items: {{ mesos_deps }}

- name: Install pre-requisite software packages (pip)
  sudo: yes
  pip: name={{ item }}
  with_items: {{ mesos_pip_deps }}
