---
# Preparations and dependencies required before the build can begin

- name: Create Mesos build directory
  file: name={{ mesos_build_dir }} state=directory mode=0755

- name: Install dependant packages
  sudo: yes
  yum: name={{ item }} state=present
  with_items: mesos_build_deps