---
# Preparations and dependencies required before the build can begin

- name: Create Mesos build directory
  sudo: yes
  file: name={{ mesos_build_dir }} state=directory
        mode=0755 owner={{ ansible_user_id }}

- name: Create link to Mesos build directory
  file: state=link name={{ mesos_build_links }}/mesos.build
        src={{ mesos_build_dir }}/mesos.git
        force=yes

- name: Install dependant packages
  sudo: yes
  yum: name={{ item }} state=present
  with_items: mesos_build_deps