---
# Preparations and dependencies required before the build can begin

- name: Create Mesos build directory
  sudo: yes
  file: name={{ mesos_build_dir }}/mesos.git state=directory
        mode=0755 owner={{ ansible_user_id }}

- name: Create mount point for Mesos build directory
  file: state=directory path={{ mesos_build_links }}/mesos.build
        mode=0755 owner={{ ansible_user_id }}

- name: Bind mount Mesos build directory
  sudo: yes
  mount: state=mounted opts=bind fstype=auto
         name={{ mesos_build_links }}/mesos.build
         src={{ mesos_build_dir }}/mesos.git

- name: Install dependant packages
  sudo: yes
  yum: name={{ item }} state=present
  with_items: mesos_build_deps