---
# Procedure to compile Mesos source code

- debug: msg="Compiling Mesos source code on = {{ ansible_distribution }}"

- name: Create mesos build directory
  file: path={{ mesos_build_links }}/mesos.build/build
        state=directory mode=755
  register: mesos_build_dir_created

- name: Cleanup Mesos build directory
  command: rm -rf {{ mesos_build_links }}/mesos.build/build/*
  when: not (mesos_build_dir_created|changed)
  tags: mesos_build_cleanup

- name: Bootstrap mesos build
  command: chdir={{ mesos_build_links }}/mesos.build ./bootstrap

- name: Build mesos from source
  command: chdir={{ mesos_build_links }}/mesos.build/build {{ item }}
  with_items:
    - ../configure --srcdir={{ mesos_build_links }}/mesos.build/
    - make -j {{ mesos_build_parallel }}
  tags:
    - build
    - mesos_build

- name: Test mesos build from source
  command: chdir={{ mesos_build_links }}/mesos.build/build {{ item }}
  with_items:
    - make -j {{ mesos_build_test_parallel }} check
  tags:
    - tests
    - mesos_build_test
