---
# Copy Mesos build artigfacts back to Ansible control host

- debug: msg="Copy Mesos build artifacts back to Ansible control host"

- name: Create Mesos build artifacts directory
  file: name={{ mesos_artifacts_dir }}/mesos state=directory mode=0755
  connection: local

- name: Transfer Mesos build artifacts to control host
  synchronize: src={{ mesos_build_links }}/mesos.build/mesos.git/build
               dest={{ mesos_artifacts_dir }}/mesos
               mode=pull
  tags:
    - copy
    - copy_mesos_artifacts
    - copy_mesos_artifacts_from

- name: Remove link to Mesos build directory
  file: state=absent name={{ mesos_build_links }}/mesos.build
