---
# Procedure to build Mesos from source

- debug: msg="*** BUILDING mesos version={{ mesos_version }}, tag={{ mesos_git_tag }} ***"

- include: build_prerequisites.yml

- name: Checkout mesos git repo
  git: repo={{ mesos_git_repo_url }} dest={{ mesos_build_dir }}/mesos.git 
       version="{{ mesos_git_tag }}"
       update=yes
       force=yes
  register: new_source_code

- include: build_process.yml
  when: mesos_build_forced or (new_source_code|changed)

- include: build_artifacts.yml
