---
# Copy Mesos build artigfacts from Ansible control host

- name: Create Mesos build artifacts directory
  sudo: yes
  file: name={{ mesos_artifacts_remote_dir }}/mesos
        state=directory mode=0755 owner={{ ansible_user_id }}

- name: Transfer Mesos build artifacts
  synchronize: src={{ mesos_artifacts_dir }}/mesos
               dest={{ mesos_artifacts_remote_dir }}
  tags:
    - copy
    - copy_mesos_artifacts
    - copy_mesos_artifacts_to

- name: Copy script to clear build dependencies files
  copy: src=disable_mesos_build_dep.sh dest=./disable_mesos_build_dep.sh
        mode=755

- name: Clear build dependencies files (to disable build deps)
  command: ./disable_mesos_build_dep.sh {{ mesos_artifacts_remote_dir }}

- name: Bind mount Mesos build directory
  sudo: yes
  mount: state=mounted opts=bind fstype=auto
         name={{ mesos_build_links }}/mesos.build
         src={{ mesos_artifacts_remote_dir }}/mesos/mesos.git
