---
# Copy Mesos build artigfacts from Ansible control host

- name: Create Mesos build artifacts directory
  sudo: yes
  file: name={{ mesos_artifacts_remote_dir }}/mesos
        state=directory mode=0755 owner={{ ansible_user_id }}

- name: Transfer Mesos build artifacts
  synchronize: src={{ mesos_artifacts_dir }}/mesos
               dest={{ mesos_artifacts_remote_dir }}
  tags:
    - copy
    - copy_mesos_artifacts
    - copy_mesos_artifacts_to

- name: Create mount point for Mesos build directory
  file: state=directory path={{ mesos_build_links }}/mesos.build

- name: Bind mount Mesos build directory
  sudo: yes
  mount: state=mounted opts=bind fstype=auto
         name={{ mesos_build_links }}/mesos.build
         src={{ mesos_artifacts_remote_dir }}/mesos/mesos.git
