---
# Cleaning up after Mesos installation from source

- name: Unmount Mesos build directory
  sudo: yes
  mount: state=unmounted name={{ mesos_build_links }}/mesos.build

- name: Remove mount point of Mesos build directory
  file: state=absent path={{ mesos_build_links }}/mesos.build
