---
# Cleaning up after Mesos installation from source

- name: Unmount Mesos build directory
  sudo: yes
  mount: state=absent name={{ mesos_build_links }}/mesos.build src=what-is-this-needed
         fstype=auto
