---
# Install and configure Mesos slave

# ---------------------------------------------------------------------
#  Installation 
# ---------------------------------------------------------------------

# - debug: msg="packages = {{ mesos_slave_pkgs }}"

- name: Install Mesos slave packages
  yum: state=present name={{ item }}
  when: ansible_pkg_mgr == "yum"
  with_items: mesos_slave_pkgs
  notify:
    - Enable Mesos slave service
#    - Enable Docker daemon
#    - Restart Docker daemon

- name: Cleanup old Mesos slave info
  file: path="{{ mesos_work_dir }}/meta/slaves/latest" state=absent

# Docker service ------------------------------------------------------

- debug: msg="Making sure Docker service is enabled and restarted"

- name: Enable Docker daemon
  service: name={{ docker_svc }} state=stopped enabled=yes

- name: Restart Docker daemon
  service: name={{ docker_svc }} state=restarted

# ---------------------------------------------------------------------
#  Configuration 
# ---------------------------------------------------------------------

# FIXME: this is very OS-specific, should be moved to separate task, one of each OS

- name: Create mesos slave configuration files
  template: src="{{ item.key }}" dest="{{ item.value }}"
  with_dict: slave_config
  notify:
    - Restart Mesos slave service
