---
# Install and configure Mesos slave

# ---------------------------------------------------------------------
#  Installation 
# ---------------------------------------------------------------------

- debug: msg="packages = {{ mesos_slave_pkgs }}"

- name: Install Mesos slave packages
  yum: state=present name={{ item }}
  when: ansible_pkg_mgr == "yum"
  with_items: mesos_master_pkgs
#  notify:
#    - Enable Mesos slave service

# ---------------------------------------------------------------------
#  Configuration 
# ---------------------------------------------------------------------
